[package]
name = "emerald-rs"
version = "0.23.0"
authors = ["Dmitry Ulanov <dulanov@gmail.com>", "Constantine Kryvomaz <kostiyantynk@gmail.com>", "Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "Ethereum Classic secure account management core libary"
homepage = "http://etcdevteam.com"
repository = "https://github.com/ETCDEVTeam/emerald-rs"
documentation = "https://docs.rs/emerald-core"
keywords = ["ethereum-classic", "blockchain", "ffi", "crypto-wallet", "cold-storage"]
categories = ["embedded", "external-ffi-bindings"]
readme = "README.md"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "ETCDEVTeam/emerald-rs" }
appveyor = { repository = "ETCDEVTeam/emerald-rs" }

[lib]
name = "emerald_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[target.'cfg(unix)'.dependencies]
rust-scrypt = "1.0"

[dependencies]
time = "0.1"
futures = "0.1"
wasm-bindgen = "0.2.8"
jsonrpc-core = "8.0"
jsonrpc-http-server = "8.0"
lazy_static = "0.2"
log = "0.3"
regex = "0.2"
hex = "0.2"
serde = {version = "1.0", default_features = false}
serde_json = "1.0"
serde_derive = "1.0"
glob = "0.2"
uuid = { version = "0.5", features = ["serde", "v4"] }
# DO NOT MERGE WITH THIS REPO POINTING AT MASTER!
rust-crypto = {version = "^0.2", default_features = false}
secp256k1 = {version = "0.9", default_features = false}
rand = "0.3"
byteorder="1.0"
ethabi = "2.0.0"
num = {version = "0.1.40", default_features = false}
bitcoin = {version = "0.13.1", default_features = false}
# optional dependencies
emerald-rocksdb =  { git = "https://github.com/ETCDEVTeam/emerald-rocksdb.git", branch = "master", optional = true }
hyper = { version = "0.11", default_features = false, optional = true }
reqwest = { version = "0.6", optional = true }
clippy = {version = "0.0", optional = true}
chrono = "0.4"
hidapi = "0.4"

[dev-dependencies]
tempdir = "0.3"
quickcheck = "0.4"
# quickcheck_macros = "0.4"

[features]
default = ["http", "emerald-rocksdb"]
http = ["hyper", "reqwest"]
dev = ["clippy"]
fs-storage = []
