[package]
name = "emerald-rs"
version = "0.26.0"
authors = ["Dmitry Ulanov <dulanov@gmail.com>", "Constantine Kryvomaz <kostiyantynk@gmail.com>", "Stewart Mackenzie <setori88@gmail.com>", "Wei Tang <hi@that.world>"]
description = "Ethereum Classic secure account management core libary"
homepage = "http://etclabscore.com"
repository = "https://github.com/etclabscore/emerald-rs"
documentation = "https://docs.rs/emerald-core"
keywords = ["ethereum-classic", "blockchain", "ffi", "crypto-wallet", "cold-storage"]
categories = ["embedded", "external-ffi-bindings"]
readme = "README.md"
license = "Apache-2.0"

[badges]
travis-ci = { repository = "etclabscore/emerald-rs" }
appveyor = { repository = "etclabscore/emerald-rs" }

[lib]
name = "emerald_rs"
path = "src/lib.rs"
#crate-type = ["rlib", "cdylib"]

[dependencies]
time = "0.1.42"
futures = "0.1.25"
jsonrpc-core = "10.0.1"
jsonrpc-http-server = "10.0.1"
lazy_static = "1.2.0"
log = "0.4.6"
regex = "1.1.0"
hex = "0.3.2"
serde = "1.0.87"
serde_json = "1.0.38"
serde_derive = "1.0.87"
glob = "0.2.11"
uuid = { version = "0.7.2", features = ["serde", "v4"] }
secp256k1 = { version = "0.12.2", features = ["rand"] }
rand = "0.6.5"
byteorder= "1.3.1"
ethabi = "6.1.0"
num = "0.2.0"
bitcoin = "0.16.0"
aes-ctr = "0.3.0"
sha2 = "0.8.0"
sha3 = "0.8.1"
pbkdf2 = "0.3.0"
scrypt = "0.2.0"
hmac = "0.7.0"
# optional dependencies
emerald-rocksdb =  { version = "100.0.0", optional = true }
hyper = { version = "0.12.23", optional = true }
reqwest = { version = "0.9.9", optional = true }
clippy = { version = "0.0.302", optional = true }
chrono = "0.4.6"
hidapi = "0.5.0"

[dev-dependencies]
tempdir = "0.3.7"
quickcheck = "0.8.1"
# quickcheck_macros = "0.4"

[features]
default = ["http", "emerald-rocksdb"]
http = ["hyper", "reqwest"]
dev = ["clippy"]
fs-storage = []
